### ISSUE TITLE
Using @[0] to get nested values

### ISSUE THREAD

**Issue by v3rmin** [joshbuddy/jsonpath#108]
I found some differences when I was testing at http://jsonpath.com/

**NOTE: The phone numbers are wrapped in an Array.**

## JSONPath.com
<img width="1110" alt="jsonpath_online" src="https://user-images.githubusercontent.com/799089/52211199-76c89c00-2889-11e9-826f-533ee1b8dc93.png">

## jsonpath ruby gem
```ruby
require 'jsonpath'

json = <<-JSON
{
  "phoneNumbers": [
    [{
      "type"  : "iPhone",
      "number": "0123-4567-8888"
    }],
    [{
      "type"  : "home",
      "number": "0123-4567-8910"
    }]
  ]
}
JSON

path = JsonPath.new("$.phoneNumbers[?(@[0].type == 'home')]")

p path.on(json) # => [[{"type"=>"iPhone", "number"=>"0123-4567-8888"}], [{"type"=>"home", "number"=>"0123-4567-8910"}]]
```
As you can see both numbers are returned when using the gem instead of only the home number. Is this kind of path not supported by the gem?

**Comment by v3rmin** [comment]
Notify @Skarlso

**Comment by Skarlso** [comment]
@v3rmin Hi. Interesting... So indexing is supported by default in Jsonpath. Could you try doing something like this? 

```
$.phoneNumbers[0][?(@.type == 'home')]
```

**Comment by v3rmin** [comment]
`$.phoneNumbers[0][?(@.type == 'home')]` returns empty Array `[]`

**Comment by v3rmin** [comment]
I want to have the same output/result as I got from jsonpath.com

**Comment by Skarlso** [comment]
Oh. I seeee..... Jsonpath returns the nested item as a single entity and does not consider that it's a nested array. 🤔 I'll take a deeper look at this.

**Comment by Skarlso** [comment]
@v3rmin This works as a workaround:

```ruby
path = JsonPath.new("$.phoneNumbers[(@.length-1)][?(@.type == 'home')]")
```

`@.0` doesn't work right now. I'll fix that. So after that this will work:

```ruby
path = JsonPath.new("$.phoneNumbers[(@.0)][?(@.type == 'home')]")
```

Where @.0 is basically the indexing part. Is that okay?

**Comment by Skarlso** [comment]
Wait. This is odd. [1] is working to get the right item...

**Comment by Skarlso** [comment]
Alright. I'm going to tackle this now. I had some very busy moments in my life, but I'm back for this.
