### ISSUE TITLE
support filter by childnode value

### ISSUE THREAD

**Issue by zhiyuchen** [joshbuddy/jsonpath#11]
Seems this is not currently supported, calling the method below returns an error:
NoMethodError: undefined method `price' for "reference":String

JsonPath.on("{ \"store\": {\"book\": [{ \"category\": \"reference\", \"price\": 8.95} ] }}", "$..book[?(@.price==8.95)].category")

**Comment by greyblake** [comment]
@joshbuddy @zhiyuchen Looks like it fixed already:)
