### ISSUE TITLE
TypeError: 0 is not a symbol nor a string exception

### ISSUE THREAD

**Issue by incubus** [joshbuddy/jsonpath#121]
Hi!

 I got an exception
```
> JsonPath.new('$.responsesData.responses.*[*]').on(data)
TypeError: 0 is not a symbol nor a string
from /Users/incubus/.rvm/gems/ruby-2.6.5/gems/jsonpath-1.0.5/lib/jsonpath/enumerable.rb:17:in `each'

```
with this data https://pastebin.com/enRUR5EH .

But it works in evaluators:

![image](https://user-images.githubusercontent.com/63255/67831344-fafa3800-fb18-11e9-9385-03231fdfdc61.png)

![image](https://user-images.githubusercontent.com/63255/67831365-11a08f00-fb19-11e9-84f1-13272a03b31f.png)

 Something is wrong with my path? Thanks!

Best regards,
Alexander

**Comment by Skarlso** [comment]
Hi @incubus. I'll take a look later on. I'm a bit busy right now, but I'll get back to you! :)
