### ISSUE TITLE
Requires tag for new release

### ISSUE THREAD

**Issue by mikemol** [joshbuddy/jsonpath#122]
https://github.com/joshbuddy/jsonpath/commit/56c2fd0b356e463883bc06cf71289da3f27d9830 is not tagged; it doesn't show up in any ref but master.

**Comment by Skarlso** [comment]
Interesting. I'll take a look.

**Comment by Skarlso** [comment]
https://rubygems.org/gems/jsonpath it is released though? 🤔

**Comment by mikemol** [comment]
I'm trying to use the thing for work, but I'm required to be able to point
to a precise code state if the thing is open-source. So I look for git
tags, since that's about the most precise I could get. I don't have a solid
way of saying which git commit corresponds to the current state on
rubygems.org.

:wq

**Comment by Skarlso** [comment]
Okay not to worry. I'll create a tag
😊

**Comment by Skarlso** [comment]
@mikemol sorry this took so long. I'm busy at work. I created the tag for you. Hopefully this helps.

**Comment by mikemol** [comment]
Thanks! Would be cool if you could automate this somehow. But honestly it'd be slicker of Github provided a mechanism to do that automatically in response to integration with sites like rubygems.org.
