### ISSUE TITLE
Please don't depend on to_regexp

### ISSUE THREAD

**Issue by grosser** [joshbuddy/jsonpath#125]
It seems like an unnecessary dependency and also adds a global monkey-patch

**Comment by grosser** [comment]
@Skarlso 🙏 
I can make the PR if you want

**Comment by Skarlso** [comment]
@grosser sure, please feel free to open one if it's okay I'll merge and release it. Thanks!

**Comment by grosser** [comment]
https://github.com/joshbuddy/jsonpath/pull/128

**Comment by Skarlso** [comment]
@grosser Gem has been released, thank you for your contribution. :)

**Comment by Skarlso** [comment]
https://rubygems.org/gems/jsonpath/versions/1.0.6
