### ISSUE TITLE
Jsonpath with $ keyname not working

### ISSUE THREAD

**Issue by jeevamanivel** [joshbuddy/jsonpath#153]
We have a JSON that has $ as keyname. ex. **{"test":{"$":"success"}}**
When we try JsonPath.on(jsonobj, "$.test.$") - This returns empty array, it should have returned "success".
Is there a way to handle this scenario?

JsonPath.fetch_all_path(data) returns this JsonPath also - "$.test.$", but its not able to extract value of this JsonPath

**Comment by tisba** [comment]
This was fixed in https://github.com/joshbuddy/jsonpath/pull/157

**Comment by jeevamanivel** [comment]
> This was fixed in #157

Thanks! this is working now!

**Comment by tisba** [comment]
Great! Maybe you want to close the issue then, @jeevamanivel?

**Comment by jeevamanivel** [comment]
Its working now, hence closing the issue
