### ISSUE TITLE
Any plan for a new release?

### ISSUE THREAD

**Issue by deivinsontejeda** [joshbuddy/jsonpath#166]
I watched some changes main branch even bumpy a new version, but the latest release was in 2020... So, is there any plan to a new release?

**Comment by joshbuddy** [comment]
I see the last release here https://rubygems.org/gems/jsonpath as October 12, 2023. I'm curious where you're getting 2020 from.

**Comment by deivinsontejeda** [comment]
Yup, you are right

**Comment by deivinsontejeda** [comment]
I was looking here... https://github.com/joshbuddy/jsonpath/releases
