### ISSUE TITLE
Are any string functions implemented?

### ISSUE THREAD

**Issue by shadoi** [joshbuddy/jsonpath#17]
Seems from the code there's no way to do something equivalent to this in XPath:

(Pulled from the example on http://en.wikipedia.org/wiki/XPath)

/wikimedia/projects/project[@name="Wikipedia"]/editions/edition/text()

Is it not possible to filter based on string values yet?  Are there any plans to implement this, along with the other string functions?

**Comment by Skarlso** [comment]
Going to address this issue.

**Comment by Skarlso** [comment]
@shadoi what functionality are you looking for based on a real json example which you couldn't do with the help of currently supported functionality? I mean, I see the point of `@name` in that sample XML. But that's an xml node with an attribute.
