### ISSUE TITLE
Element wildcard (*) is not supported on intermediate elements and produces wrong results on terminal nodes

### ISSUE THREAD

**Issue by eliaslevy** [joshbuddy/jsonpath#30]
This works

``` ruby
JsonPath.on({'a'=>{'b'=>{'c'=>1}}}, '$.a.*') # [{"b"=>{"c"=>1}}] 
```

but note is produces the wrong result.  It should generate `[{"c"=>1}]`.

This doesn't work

``` ruby
JsonPath.on({'a'=>{'b'=>{'c'=>1}}}, '$.a.*.c') # []
```

It should return `[1]`.

Note that http://jsonpath.curiousconcept.com/ produces the expected results in both cases.

**Comment by Skarlso** [comment]
Fixed this.

**Comment by Skarlso** [comment]
Fixed this in an upcoming PR.
