### ISSUE TITLE
gsub fails for where selectors

### ISSUE THREAD

**Issue by jpsimonroy** [joshbuddy/jsonpath#32]
Try the below in the specs:
JsonPath.for(@object).gsub!("$..book[?(@['price'] > 20)]") { |p| p + 10 }

It fails with trace:
NoMethodError: undefined method `+' for nil:NilClass
    from (irb):139:in`block in irb_binding'
    from /Users/simon/.rvm/gems/ruby-2.1.2@lookist/gems/jsonpath-0.5.6/lib/jsonpath/enumerable.rb:97:in `call'
    from /Users/simon/.rvm/gems/ruby-2.1.2@lookist/gems/jsonpath-0.5.6/lib/jsonpath/enumerable.rb:97:in`yield_value'
    from /Users/simon/.rvm/gems/ruby-2.1.2@lookist/gems/jsonpath-0.5.6/lib/jsonpath/enumerable.rb:15:in `each'
    from /Users/simon/.rvm/gems/ruby-2.1.2@lookist/gems/jsonpath-0.5.6/lib/jsonpath/enumerable.rb:38:in`block (2 levels) in each'
    from /Users/simon/.rvm/gems/ruby-2.1.2@lookist/gems/activesupport-4.1.6/lib/active_support/core_ext/range/each.rb:7:in `each'
    from /Users/simon/.rvm/gems/ruby-2.1.2@lookist/gems/activesupport-4.1.6/lib/active_support/core_ext/range/each.rb:7:in`each_with_time_with_zone'
    from /Users/simon/.rvm/gems/ruby-2.1.2@lookist/gems/jsonpath-0.5.6/lib/jsonpath/enumerable.rb:35:in `block in each'
    from /Users/simon/.rvm/gems/ruby-2.1.2@lookist/gems/jsonpath-0.5.6/lib/jsonpath/enumerable.rb:24:in`each'
    from /Users/simon/.rvm/gems/ruby-2.1.2@lookist/gems/jsonpath-0.5.6/lib/jsonpath/enumerable.rb:24:in `each'
    from /Users/simon/.rvm/gems/ruby-2.1.2@lookist/gems/jsonpath-0.5.6/lib/jsonpath/enumerable.rb:29:in`block in each'
    from /Users/simon/.rvm/gems/ruby-2.1.2@lookist/gems/jsonpath-0.5.6/lib/jsonpath/enumerable.rb:24:in `each'
    from /Users/simon/.rvm/gems/ruby-2.1.2@lookist/gems/jsonpath-0.5.6/lib/jsonpath/enumerable.rb:24:in`each'
    from /Users/simon/.rvm/gems/ruby-2.1.2@lookist/gems/jsonpath-0.5.6/lib/jsonpath/enumerable.rb:78:in `block in each'
    from /Users/simon/.rvm/gems/ruby-2.1.2@lookist/gems/jsonpath-0.5.6/lib/jsonpath/enumerable.rb:78:in`each'
    from /Users/simon/.rvm/gems/ruby-2.1.2@lookist/gems/jsonpath-0.5.6/lib/jsonpath/enumerable.rb:78:in `each'
    from /Users/simon/.rvm/gems/ruby-2.1.2@lookist/gems/jsonpath-0.5.6/lib/jsonpath/enumerable.rb:18:in`each'
    from /Users/simon/.rvm/gems/ruby-2.1.2@lookist/gems/jsonpath-0.5.6/lib/jsonpath/enumerable.rb:20:in `each'
    from /Users/simon/.rvm/gems/ruby-2.1.2@lookist/gems/jsonpath-0.5.6/lib/jsonpath/proxy.rb:40:in`_gsub'
    from /Users/simon/.rvm/gems/ruby-2.1.2@lookist/gems/jsonpath-0.5.6/lib/jsonpath/proxy.rb:15:in `gsub!'
    from (irb):139
    from /Users/simon/.rvm/rubies/ruby-2.1.2/bin/irb:11:in`<main>'

**Comment by Skarlso** [comment]
Because the correct for the assert is this: `JsonPath.for(@object).gsub!('$..book.price[?(@ > 20)]') { |p| p + 10 }`
