### ISSUE TITLE
Curation of this gem and maintenance of this Gem

### ISSUE THREAD

**Issue by Skarlso** [joshbuddy/jsonpath#40]
Hi.

So, I'm in desperate need of an update for this Gem and it hasn't been curated / updated in a LONG while, even though there are some much needed pending PRs in it. 

I'd be happy to take over the maintenance of it if you would like me to @joshbuddy. 

Cheers,
Skarlso.

**Comment by PositiveAlex** [comment]
That would be awesome if you curate this repo!

**Comment by Skarlso** [comment]
Hey @PositiveAlex. Pop over to my repos. You find it there. ☺️
https://github.com/Skarlso/jsonpathv2

**Comment by joshbuddy** [comment]
@Skarlso Hey, do you want to have access to this repo and the gem? Send me an email at joshbuddy@gmail.com

**Comment by Skarlso** [comment]
Thanks man!
