### ISSUE TITLE
Relationship to JSON Pointer spec?

### ISSUE THREAD

**Issue by bf4** [joshbuddy/jsonpath#43]
@joshbuddy Is this spec meant to complement the [JSON Pointer RFC 6901](https://tools.ietf.org/html/rfc6901) or compete with it?

**Comment by Skarlso** [comment]
@bf4 I'm gonna asses this soon. :)

**Comment by Skarlso** [comment]
@bf4 It doesn't aim to do either. It's actually a Ruby implementation of an XPath search pattern described here: http://goessner.net/articles/JsonPath/.

Thus, you should really ask rather, what's the relationship of that XPath to that RFC. Though if I understood that RFC, this has nothing to do with it. So I guess it's a competitor of sort. :)

**Comment by bf4** [comment]
Yeah, I was thinking it's a competitor that's superseded jsonpath
