### ISSUE TITLE
Unable to parse `dict.*.key` type query

### ISSUE THREAD

**Issue by pts-kevinqiu** [joshbuddy/jsonpath#44]
Here's a sample script:
```
require 'jsonpath'

json = <<-HEREDOC
{
  "nodes": {
    "foo": {
      "duh": 1
    },
    "bar": {
      "duh": 2
    },
    "quux": {
      "duh": 3
    }
  }
}
HEREDOC

path = JsonPath.new('$.nodes.*.duh')
puts path.on(json)
```

Running the script produces empty result, while I'm expecting `[1, 2, 3]`. Testing the json on http://www.jsonquerytool.com/#/JSONPath gives me the right result:

![image](https://cloud.githubusercontent.com/assets/22983808/24879317/79da4dc6-1e04-11e7-9495-2aea49522014.png)

**Comment by Skarlso** [comment]
Yes, intermediary wildcards aren't working yet. You can work around this using `[?(@)]` for new instead of the `*`. I'll try to work out a nicer way of doing it.

**Comment by Skarlso** [comment]
Fixed this in an upcoming PR.
