### ISSUE TITLE
New Collaborator

### ISSUE THREAD

**Issue by Skarlso** [joshbuddy/jsonpath#45]
Hey folks. 

I've been added as a collaborator, so I'm going to address all the issues one-by-one and apply some refactorings I already did.

Please feel free to submit new issues if you have any desires.

Cheers,
Gergely.

**Comment by barttenbrinke** [comment]
So is your fork is this gem going to be deprecated?

**Comment by Skarlso** [comment]
Hey man. 

Unsure yet. I'm gonna talk to the folks at huginn who are using my version right now.

**Comment by Skarlso** [comment]
@barttenbrinke gonna talk with the huginn folks. I'll probably deprecate mine as this one is more widely used.

**Comment by Skarlso** [comment]
Tracking here as well. I'll create a pull to Huginn once, I'm ready, and deprecate my own copy of this Gem.

**Comment by Skarlso** [comment]
Submitted the PR to Huginn folk to remove the need for my Gem.

**Comment by Skarlso** [comment]
huginn/huginn/#1996

**Comment by Skarlso** [comment]
Thanks for the nice folks at huginn my PR has been merges. I'm closing this one.
