### ISSUE TITLE
Support for OR (||) operator?

### ISSUE THREAD

**Issue by johnallen3d** [joshbuddy/jsonpath#49]
I've tried a few things based on [suggestions in this post](http://stackoverflow.com/questions/23897661/or-operator-in-jsonpath) but am having no luck. Obviously there are many different implementations of JSONPath so I'm wondering if this one has support for an `OR` operator. 

As an illustration, the following example works with the [online evaluator](http://jsonpath.com/):

```json
// JSON
{
  "firstName": "John",
  "phoneNumbers": [
    {
      "type"  : "iPhone",
      "number": "0123-4567-8888"
    },
    {
      "type"  : "home",
      "number": "0123-4567-8910"
    }
  ]
}
```

```
// query
$.phoneNumbers[?(@.type == 'home' || @.type == 'iPhone')]
```

```json
// desired output
[
  {
    "type": "iPhone",
    "number": "0123-4567-8888"
  },
  {
    "type": "home",
    "number": "0123-4567-8910"
  }
]
```

**Comment by Skarlso** [comment]
Huh, interesting. :D Gonna check it out.

**Comment by Skarlso** [comment]
@johnallen3d Hey man. Checkout the added examples. ;)

**Comment by johnallen3d** [comment]
👍 thanks!

**Comment by Skarlso** [comment]
@johnallen3d Feel free to reopen this issue if it doesn't meat what you want.

Cheers
