### ISSUE TITLE
Do you plan to add a full implementation of `?()`

### ISSUE THREAD

**Issue by 1e1** [joshbuddy/jsonpath#54]
As defined on http://goessner.net/articles/JsonPath/
The `?() ` means *a filter (script) expression*.

An example from http://stackoverflow.com/questions/30030652/filter-the-json-according-to-string-in-an-array-in-jsonpath
explains we can use the valid Javascript Jsonpath: `$.Books.History[?(@.Tags.indexOf('Indian') != -1)]` 

The Ruby version should be: `$.Books.History[?(@.Tags.include?('Indian'))]`?

In this case which trick solves this issue?

**Comment by Skarlso** [comment]
Hi.

Thanks for submitting an issue.

There is no `underlying` javascript which this gem executes, so there are no methods like `include?` or `indexOf`. Though you did bring my attention to Tags which is an array. I think we are lacking a facility to check values in that. :/

**Comment by Skarlso** [comment]
So there is something working.. I might just need to extend on this.

```ruby
assert_equal ['asdf'], JsonPath.new("$.store.book..tags[?(@ == 'asdf')]").on(@object)
```
But I can't get it to return the node for now. It returns just that tag. 

And tag looks like this: 

```ruby
      'book' => [
        { 'category' => 'reference',
          'author' => 'Nigel Rees',
          'title' => 'Sayings of the Century',
          'price' => 9,
          'tags' => ['asdf', 'asdf2']},
...
```

**Comment by Voomer** [comment]
in version 5.8.0 this expression worked:
$.acceptNewTasks.[?(@.taskEndpoint == "mps/awesome")].lastTaskPollTime

Now there is an infinite loop in the Parser.parse_exp function in versions 7.0.0 and up.

**Comment by Skarlso** [comment]
Ahh. Thanks for the report. I'm gonna address it ASAP.

**Comment by Skarlso** [comment]
Interesting. That looks like something that should have worked though. Hmmm. I bet it's the `/`.

**Comment by Skarlso** [comment]
@1e1 I got it to a point where you can basically match against an element in an array. But that will only return the matched element. The node is not back followed.

I'll work on this some more later on.

**Comment by Skarlso** [comment]
```ruby
  def test_dig_return_string
    assert_equal ['asdf'], JsonPath.new("$.store.book..tags[?(@ == 'asdf')]").on(@object)
    assert_equal [], JsonPath.new("$.store.book..tags[?(@ == 'not_asdf')]").on(@object)
  end
```

for

```ruby
      'book' => [
        { 'category' => 'reference',
          'author' => 'Nigel Rees',
          'title' => 'Sayings of the Century',
          'price' => 9,
          'tags' => ['asdf', 'asdf2']},
```

**Comment by Skarlso** [comment]
so, because of some of the design choices that have been made, the expression comes in like this:

```ruby
exp : ['tags']['include']?'noasdf'
```

Now, constructing something useful out of this is not impossible, but alas, there is no way of finding out, if in this situation 'include' is a function call or an element.

A help would be if I could restrict function syntax to question marks at the end. But that would mean that nothing else can be called, like `size` for example.
