### ISSUE TITLE
Infinite loop on parsing expression

### ISSUE THREAD

**Issue by Skarlso** [joshbuddy/jsonpath#57]
>in version 5.8.0 this expression worked:
>$.acceptNewTasks.[?(@.taskEndpoint == "mps/awesome")].lastTaskPollTime

>Now there is an infinite loop in the Parser.parse_exp function in versions 7.0.0 and up.

Ping @Voomer.

**Comment by Skarlso** [comment]
Yep, it is the slash. How mediocre.

**Comment by Voomer** [comment]
Thanks!
