### ISSUE TITLE
It's alive!

### ISSUE THREAD

**Issue by Skarlso** [joshbuddy/jsonpath#66]
Don't let the lack of updates discourage you.

There aren't any because it's pretty much feature complete. I might still hack around on it to improve it in some ways, but there aren't too many things I can do at this point.

I'm promptly answering issues though, if any should arise.

Cheers,
Gergely.

**Comment by joshbuddy** [comment]
Given what a stellar job you've been doing with this, gonna close this issue :)

You're the best @Skarlso!

**Comment by Skarlso** [comment]
@joshbuddy Thanks, man! :)
