### ISSUE TITLE
Support '@' in jsonpath filter

### ISSUE THREAD

**Issue by melsawy** [joshbuddy/jsonpath#67]
I'd like to filter json+ld data so I should include `@` in jsonpath
i.e. `$.mentions[?(@['@type'] == 'Place')]` I got empty result although my json+ld data has a `@type == Place` 
the data format is:
```
jsonld = {
   "mentions":[
      {
         "name":"Delimara Powerplant",
         "identifier":"krzana://took/powerstation/Delimara Powerplant",
         "@type":"Place",
         "geo":{
            "latitude":35.83020073454,
            "longitude":14.55602645874
         }
      }
   ]
}
```

the full jsonpath is `JsonPath.new("$.mentions[?(@['@type'] == 'Place')]").on(jsonld)`

**Comment by Skarlso** [comment]
Oh, cool. Interesting. I'm on it. 👍

**Comment by Skarlso** [comment]
That's unfortunate. The `@` is a special character for JsonPath. I'll have to work around that somehow.

**Comment by Skarlso** [comment]
Fixed. Should be okay now. Please reopen in case it doesn't work as expected. @melsawy.

**Comment by melsawy** [comment]
:+1:  works well thanks @Skarlso

**Comment by Skarlso** [comment]
Awesome! Thanks. :-)

**Comment by viggis75** [comment]
Hi @Skarlso and @melsawy! I'm also struggling using Filters and Predicates where my JSON is JSON-LD containing @ fields.

Given I have an array of JSON-LD that looks similar to this (I cut some of it to make it simpler to read):
{
	"@context": "http://schema.org/",
	"@type": "Order",
	"seller": {
		"@type": "Organization",
		"name": "NOT KNOWN"
	},
	"broker": {
		"@type": "Organization",
		"name": "Foo Org"
	},
	"customer": {
		"@type": "Person",
		"name": "Person A Name",
		"telephone": "1122334455"
	},
	"orderDate": "2016-05-24",
	"orderDelivery": {
		"@type": "ParcelDelivery",
		"provider": {
			"@type": "Organization",
			"@id": "https://foo.io./organizations/123456789",
			"legalName": "Company B",
			"identifier": "123456789",
			"employee": {
				"@type": "Person",
				"@id": "https://foo.io./organizations/123456789/employees/00001"
			}
		},

Given the following code where I try to match on the @type on the orderDelivery: 
        Filter ordersByDriverFilter = Filter.filter(Criteria.where("orderDelivery[@type]").eq("ParcelDelivery"));
        List<Map<String, Object>> orders = JsonPath.parse(ordersAsStream).read("$[*][?]", ordersByDriverFilter);

It doesn't match, and I assume it's because I have something wrong with the construction of the where statement.

Do you see what I'm doing wrong?

**Comment by Skarlso** [comment]
Interesting. Yeah, I'm not excepting any `@` signs in a node name.
I'll fix it.

**Comment by viggis75** [comment]
btw, I just realized that I was using this lilbrary, https://github.com/json-path/JsonPath, but I might turn into using this library instead

**Comment by Skarlso** [comment]
@viggis75 Oh, can you check if it is a problem with this one as well?
