### ISSUE TITLE
Parentheses are not supported in a matcher

### ISSUE THREAD

**Issue by ryansch** [joshbuddy/jsonpath#69]
Failing test case:

```ruby
  def test_parens_in_value
    data = {
      'data' => {
        'number' => '(492) 080-3961'
      }
    }
    assert_equal [{'number'=>'(492) 080-3961'}], JsonPath.new("$.data[?(@.number == '(492) 080-3961')]").on(data)
  end
```

Output:
```
1) Failure:
TestJsonpath#test_parens_in_value [test/test_jsonpath.rb:354]:
Expected: [{"number"=>"(492) 080-3961"}]
  Actual: []
```

The failure appears to come from: https://github.com/joshbuddy/jsonpath/blob/8caab76ff047eaa3fc765834a4bb16b27163a3c9/lib/jsonpath/parser.rb#L25

**Comment by Skarlso** [comment]
Uh geez, nice catch. :)

**Comment by Skarlso** [comment]
right, that's because there is a lot of fluff in the incoming element value. Ahh geez, that going to suck. :/

**Comment by Skarlso** [comment]
Oh, it's actually easier than that.

**Comment by Skarlso** [comment]
@ryansch Fixed.

**Comment by ryansch** [comment]
Thanks!
