### ISSUE TITLE
Cannot `gsub` with a PATH_ALL expression. 

### ISSUE THREAD

**Issue by dadiv** [joshbuddy/jsonpath#73]
First, thanks for making jsonpath! It's great!

Second, can you help with this error? Should it not be possible to do the following?

```
JsonPath.for('{"a": "b"}').gsub('$..*'){|v| v }.to_hash
```

This fails with:

```
TypeError: no implicit conversion of nil into Hash
	from /Users/david/projects/soomo/vendor/bundle/ruby/2.3.0/gems/jsonpath-0.8.10/lib/jsonpath/enumerable.rb:103:in `replace'
	from /Users/david/projects/soomo/vendor/bundle/ruby/2.3.0/gems/jsonpath-0.8.10/lib/jsonpath/enumerable.rb:103:in `yield_value'
	from /Users/david/projects/soomo/vendor/bundle/ruby/2.3.0/gems/jsonpath-0.8.10/lib/jsonpath/enumerable.rb:15:in `each'
	from /Users/david/projects/soomo/vendor/bundle/ruby/2.3.0/gems/jsonpath-0.8.10/lib/jsonpath/enumerable.rb:18:in `each'
	from /Users/david/projects/soomo/vendor/bundle/ruby/2.3.0/gems/jsonpath-0.8.10/lib/jsonpath/enumerable.rb:18:in `each'
	from /Users/david/projects/soomo/vendor/bundle/ruby/2.3.0/gems/jsonpath-0.8.10/lib/jsonpath/enumerable.rb:20:in `each'
	...
```

I get the same failure with:

```
JsonPath.for('{}').gsub('$..*'){|v| v }
```

I am able to do:

```
JsonPath.for('{"a": "b"}').gsub('$..a'){|v| v.is_a?(String) ? v.upcase : v }.to_hash
```

with the expected results. My particular use case is to operate on all the strings contained within the document in the block given to `#gsub`.

**Comment by Skarlso** [comment]
Hey. Thanks very much in the name of the creator as well as mine. 👍 

Also thanks for submitting a ticket. :)

I'll take a look!

**Comment by Skarlso** [comment]
Alright. So, how this works is, that you can `gsub` for all elements if the element you are replacing is that same structure as the element you are using.

So, in the above example you can gsub if you are using the same structure like this:

```ruby
    h = { 'a' => 'b' }
    res = JsonPath.for({'b' => 'c'}).gsub('$.*') {|_| h }.to_hash
    p res
$> res => {"a"=>"b"}
```

When you are doing the `'a'` case, you are specifically selecting a node, so it knows what you are trying to replace. But `*` will not look for individual nodes. It will just replace everything with what you give it.

I hope that answers your question. If that's inconvenient for you, please tell me. I'll see what I could do. :)
