### ISSUE TITLE
Filter by root key value

### ISSUE THREAD

**Issue by NDuggan** [joshbuddy/jsonpath#82]
You should be able to filter by the value of a root element. Jayway allows this as shown in their [online evaluator](http://jsonpath.herokuapp.com/?path=$.[?(@.expensive%20==%2010)]).

**JSON**
```json
{
  "initial": true
}
```

**JsonPath**
```
$.[?(@.initial == true)]
```

-----

*Tagged as requested: @Skarlso*

**Comment by Skarlso** [comment]
Could you please try `@.initial` just simply? I'll investigate soon.

**Comment by Skarlso** [comment]
For the record, jsonpath the gem is rather using this as a guide: http://jsonpath.com/ for which the above does not work.

**Comment by Skarlso** [comment]
Hah! Try this: `$.[?(@ == true)]`. Since it's the first node, that should work. 

@NDuggan

**Comment by NDuggan** [comment]
Thanks for the reply @Skarlso. I did in fact try using `@ == true` before posting but that didn't work.

Also without referencing the key you could end up filtering by the wrong element, e.g.:
```
{
  "initial": false,
  "another": true
}
```

**Comment by Skarlso** [comment]
@NDuggan bamm! :)

```ruby
  def test_another
    json = {
      initial: true,
      not: true
    }.to_json
    p JsonPath.on(json, "$.initial[?(@)]")
  end
```

**Comment by NDuggan** [comment]
@Skarlso awesome, thank you very much.

I can also confirm that your examples work and the following also works.
```
json = {initial: 'foo'}.to_json
JsonPath.on(json, "$.initial[?(@ == 'foo')]")
=> ["foo"]
```

Is there any reason though, that you cannot do this:
```
json = {initial: true}.to_json
JsonPath.on(json, "$.initial[?(@ == true)]")
=> []
```

**Comment by Skarlso** [comment]
Huh. That is odd. I should think that that should work as well. I'll investigate.

**Comment by Skarlso** [comment]
Sorry, I'm swamped, going to look at it today maybe, but tomorrow latest.

**Comment by Skarlso** [comment]
Ah, because I strip out `@`... so the expression becomes `"== true"` which won't work. That's why you can't do this. I'm gonna fix it.

**Comment by Skarlso** [comment]
So this is quiet odd. 

`$.[?(@.initial == true)]` should actually work fine. :/

```ruby
el: true; operator: ==; operand: true
ret = el.send(operator.strip, operand)
```

Return false. :O

**Comment by Skarlso** [comment]
It's a string. :/ Argh. Of course. It's the same problem as with the `false` thing.

**Comment by Skarlso** [comment]
works now as it does with Jayway's parser: 

```json
{
    "initial": true,
    "second": true,
}
```

Path: `$.[?(@.initial == true)]`

Result:

```json
[
   {
      "initial" : true,
      "second" : true
   }
]
```

@NDuggan Is that okay?

**Comment by Skarlso** [comment]
Also, fixed the parser so that it properly defines `true` and `false` now. :)

**Comment by NDuggan** [comment]
@Skarlso sorry I was away for a few days, I'm going to pull the latest version and give it a go! 👍

**Comment by NDuggan** [comment]
@Skarlso can confirm that it now worked using `$.[?(@.initial == true)]` which is perfect.

Thanks again for your quick response and action! 🥇

**Comment by Skarlso** [comment]
You're welcome. Thanks for testing and reporting the issue.
