### ISSUE TITLE
Newlines make JsonPath hang

### ISSUE THREAD

**Issue by NDuggan** [joshbuddy/jsonpath#84]
I currently allow users to enter JsonPaths via a textarea which I then split on `/\R/`, but before I implemented the split functionality I noticed my background jobs were hanging/frozen.

**How to recreate**
```
json = { initial: true }.to_json

success_path = "$.initial"
JsonPath.on(json, success_path)
# => [true]

broken_path = "$.initial\n"
JsonPath.on(json, broken_path)
# just hangs, doesn't cause an exception or anything…
```

-----

@Skarlso

**Comment by Skarlso** [comment]
going to investigate soon

**Comment by Skarlso** [comment]
Yeah this is on the parser not recognising the new line as a character I think. ah. What a pain in the ars.

**Comment by Skarlso** [comment]
Oh lol, this is the initial scanner dying. Hah. Just need to strip that new line. Everything works fine. nothing to see here.

**Comment by NDuggan** [comment]
Perfect. I wasn't planning on passing it any newlines, I just happened to do it by mistake so thought I'd report it. Thanks for the quick fix though! 👍

I've pulled the update and confirm the newline thing no longer breaks things.
