### ISSUE TITLE
Seems to have problem when there is single quote in value

### ISSUE THREAD

**Issue by junzhuang** [joshbuddy/jsonpath#96]
json_string = [{"Analysis_Type":"King's College","Denominator":"8","Numerator":"87.50%","Measure":"7"}]

JsonPath.new('$.[?(@.Analysis_Type == "King\\'s College")]').on(json_string) returns an emtpy array.

When I tested the query, $.[?(@.Analysis_Type == "King\\'s College")], on http://www.jsonquerytool.com/ it worked.

**Comment by Skarlso** [comment]
Hi. Thanks for reporting it. I'll investigate ASAP.

**Comment by Skarlso** [comment]
Confirmed. I'll be fixing it shortly.
