### ISSUE TITLE
Problems using Ruby 2.5.1

### ISSUE THREAD

**Issue by neumanrq** [joshbuddy/jsonpath#98]
Hi @Skarlso 👋 

When working with [SciRuby/daru-io](https://github.com/SciRuby/daru-io) (which includes `jsonpath`) I stumbled over the following behavior: When feeding the class `JsonPath` with input containing curly braces, like `$.{index}.{name}.age`, `jsonpath` stops throwing `FrozenError (can't modify frozen String)`.

Here's a sample log to reproduce:

```bash
robin ~: ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
robin ~: gem install jsonpath
Successfully installed jsonpath-0.9.5
Parsing documentation for jsonpath-0.9.5
Done installing documentation for jsonpath after 0 seconds
1 gem installed
robin ~: irb
2.5.1 :001 > require 'jsonpath'
 => true
2.5.1 :002 > JsonPath.new("$.name")
 => #<JsonPath:0x00007f90899b8d10 @opts={}, @path=["$", "['name']"]>
2.5.1 :003 > JsonPath.new("$.{name}")
Traceback (most recent call last):
        4: from /Users/robin/.rvm/rubies/ruby-2.5.1/bin/irb:11:in `<main>'
        3: from (irb):3
        2: from (irb):3:in `new'
        1: from /Users/robin/.rvm/gems/ruby-2.5.1/gems/jsonpath-0.9.5/lib/jsonpath.rb:37:in `initialize'
FrozenError (can't modify frozen String)
```

Unfortunately I do not understand the role of the curly braces 100% yet since I was pointed to it while trying to [fix some test examples here](https://github.com/SciRuby/daru-io/blob/master/spec/daru/io/exporters/json_spec.rb#L68).

I haven't found the syntax using the curly braces in the tests of `jsonpath`, so I wonder: Is this valid syntax (and supported)? Or is this indeed not valid syntactically (so the test case should be slightly different).

Thanks fo your help!

**Comment by Skarlso** [comment]
Hi! 

Interesting. I'll look into it! :)

**Comment by Skarlso** [comment]
Interesting. As far as I can see it shouldn't matter if there is a curly bracket or not.

**Comment by Skarlso** [comment]
Oh I think it might be `nil` or something similar, which can't be modified. I'll need to debug this further.

**Comment by Skarlso** [comment]
Hi @neumanrq.

This should be all fixed now and working. Have fun thanks for reporting it!

**Comment by neumanrq** [comment]
Thanks for fixing this so quick 🚤 👍 👌
